#!/bin/bash
set -e
cd "$(dirname "$0")/../.."

rm -f tmp/*

cd test

# runs a test file with PASS/FAIL message
run_test() {
  (php "$1" && echo "PASS $1") || (echo "FAIL $1"; exit 1)
}

if [ "$1" == "" ]; then
  for test in *.php; do
    run_test "$test"
  done
else
  run_test "$1.php"
fi
