#!/bin/bash
set -e
cd "$(dirname "$0")/.."

set -x

GENERATOR_REPO="https://github.com/OpenAPITools/openapi-generator"
GENERATOR_DIR="generator"
executable="./$GENERATOR_DIR/modules/openapi-generator-cli/target/openapi-generator-cli.jar"

GENERATOR_REVISION=$(cat .generator-revision 2> /dev/null || true)
if [ "$GENERATOR_REVISION" = "" ]; then
  echo "Set a revision of swagger-codegen to use in .generator-revision"
  exit 1
fi

if ! [ -x "$(command -v mvn)" ]; then
  echo 'Error: mvn not installed, using homebrew to install' >&2
  brew install maven
fi

if [ ! -d "$GENERATOR_DIR" ]; then
  git clone "$GENERATOR_REPO" "$GENERATOR_DIR"
fi

(
  cd $GENERATOR_DIR
  if [[ "${#GENERATOR_REVISION}" -lt 40 ]]; then
    # resolve git tags / branch names
    GENERATOR_REVISION=$(git show "$GENERATOR_REVISION" --format="%H" --no-patch)
  fi
  if [[ $(cat .git/HEAD) != "$GENERATOR_REVISION" ]]; then
    git fetch
    git checkout "$GENERATOR_REVISION"
    mvn clean package
  fi
)


if [ ! -f "$executable" ]; then
  mvn clean package
fi

export JAVA_OPTS="${JAVA_OPTS} -Xmx1024M -DloggerPath=conf/log4j.properties"
java $JAVA_OPTS -jar $executable $*
