<?php
/**
 * AsyncDocTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocRaptor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocRaptor
 *
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace DocRaptor\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AsyncDocTest Class Doc Comment
 *
 * @category    Class
 * @description AsyncDoc
 * @package     DocRaptor
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AsyncDocTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AsyncDoc"
     */
    public function testAsyncDoc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
