<?php
/**
 * DocTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DocRaptor
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DocRaptor v1
 *
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DocRaptor;

/**
 * DocTest Class Doc Comment
 *
 * @category    Class
 * @description Doc
 * @package     DocRaptor
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Doc"
     */
    public function testDoc()
    {
    }

    /**
     * Test attribute "pipeline"
     */
    public function testPropertyPipeline()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {
    }

    /**
     * Test attribute "document_content"
     */
    public function testPropertyDocumentContent()
    {
    }

    /**
     * Test attribute "document_url"
     */
    public function testPropertyDocumentUrl()
    {
    }

    /**
     * Test attribute "test"
     */
    public function testPropertyTest()
    {
    }

    /**
     * Test attribute "strict"
     */
    public function testPropertyStrict()
    {
    }

    /**
     * Test attribute "ignore_resource_errors"
     */
    public function testPropertyIgnoreResourceErrors()
    {
    }

    /**
     * Test attribute "ignore_console_messages"
     */
    public function testPropertyIgnoreConsoleMessages()
    {
    }

    /**
     * Test attribute "tag"
     */
    public function testPropertyTag()
    {
    }

    /**
     * Test attribute "help"
     */
    public function testPropertyHelp()
    {
    }

    /**
     * Test attribute "javascript"
     */
    public function testPropertyJavascript()
    {
    }

    /**
     * Test attribute "referrer"
     */
    public function testPropertyReferrer()
    {
    }

    /**
     * Test attribute "callback_url"
     */
    public function testPropertyCallbackUrl()
    {
    }

    /**
     * Test attribute "prince_options"
     */
    public function testPropertyPrinceOptions()
    {
    }
}
