<?php
/**
 * PrinceOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  DocRaptor
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DocRaptor v1
 *
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace DocRaptor;

/**
 * PrinceOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description PrinceOptions
 * @package     DocRaptor
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PrinceOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PrinceOptions"
     */
    public function testPrinceOptions()
    {
    }

    /**
     * Test attribute "baseurl"
     */
    public function testPropertyBaseurl()
    {
    }

    /**
     * Test attribute "no_xinclude"
     */
    public function testPropertyNoXinclude()
    {
    }

    /**
     * Test attribute "no_network"
     */
    public function testPropertyNoNetwork()
    {
    }

    /**
     * Test attribute "no_parallel_downloads"
     */
    public function testPropertyNoParallelDownloads()
    {
    }

    /**
     * Test attribute "http_user"
     */
    public function testPropertyHttpUser()
    {
    }

    /**
     * Test attribute "http_password"
     */
    public function testPropertyHttpPassword()
    {
    }

    /**
     * Test attribute "http_proxy"
     */
    public function testPropertyHttpProxy()
    {
    }

    /**
     * Test attribute "http_timeout"
     */
    public function testPropertyHttpTimeout()
    {
    }

    /**
     * Test attribute "insecure"
     */
    public function testPropertyInsecure()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "no_author_style"
     */
    public function testPropertyNoAuthorStyle()
    {
    }

    /**
     * Test attribute "no_default_style"
     */
    public function testPropertyNoDefaultStyle()
    {
    }

    /**
     * Test attribute "no_embed_fonts"
     */
    public function testPropertyNoEmbedFonts()
    {
    }

    /**
     * Test attribute "no_subset_fonts"
     */
    public function testPropertyNoSubsetFonts()
    {
    }

    /**
     * Test attribute "no_compress"
     */
    public function testPropertyNoCompress()
    {
    }

    /**
     * Test attribute "encrypt"
     */
    public function testPropertyEncrypt()
    {
    }

    /**
     * Test attribute "key_bits"
     */
    public function testPropertyKeyBits()
    {
    }

    /**
     * Test attribute "user_password"
     */
    public function testPropertyUserPassword()
    {
    }

    /**
     * Test attribute "owner_password"
     */
    public function testPropertyOwnerPassword()
    {
    }

    /**
     * Test attribute "disallow_print"
     */
    public function testPropertyDisallowPrint()
    {
    }

    /**
     * Test attribute "disallow_copy"
     */
    public function testPropertyDisallowCopy()
    {
    }

    /**
     * Test attribute "disallow_annotate"
     */
    public function testPropertyDisallowAnnotate()
    {
    }

    /**
     * Test attribute "disallow_modify"
     */
    public function testPropertyDisallowModify()
    {
    }

    /**
     * Test attribute "debug"
     */
    public function testPropertyDebug()
    {
    }

    /**
     * Test attribute "input"
     */
    public function testPropertyInput()
    {
    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {
    }

    /**
     * Test attribute "javascript"
     */
    public function testPropertyJavascript()
    {
    }

    /**
     * Test attribute "css_dpi"
     */
    public function testPropertyCssDpi()
    {
    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {
    }

    /**
     * Test attribute "pdf_title"
     */
    public function testPropertyPdfTitle()
    {
    }
}
