<?php
/**
 * DocApiTest
 * PHP version 5
 *
 * @category Class
 * @package  DocRaptor
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DocRaptor v1
 *
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * OpenAPI spec version: 1.3.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.14
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace DocRaptor;

use \DocRaptor\Configuration;
use \DocRaptor\ApiException;
use \DocRaptor\ObjectSerializer;

/**
 * DocApiTest Class Doc Comment
 *
 * @category Class
 * @package  DocRaptor
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAsyncDoc
     *
     * .
     *
     */
    public function testCreateAsyncDoc()
    {
    }

    /**
     * Test case for createDoc
     *
     * .
     *
     */
    public function testCreateDoc()
    {
    }

    /**
     * Test case for getAsyncDoc
     *
     * .
     *
     */
    public function testGetAsyncDoc()
    {
    }

    /**
     * Test case for getAsyncDocStatus
     *
     * .
     *
     */
    public function testGetAsyncDocStatus()
    {
    }
}
