<?php
/**
 * DocApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  DocRaptor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DocRaptor
 *
 * A native client library for the DocRaptor HTML to PDF/XLS service.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace DocRaptor\Test\Api;

use \DocRaptor\Configuration;
use \DocRaptor\ApiException;
use \DocRaptor\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DocApiTest Class Doc Comment
 *
 * @category Class
 * @package  DocRaptor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAsyncDoc
     *
     * .
     *
     */
    public function testCreateAsyncDoc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createDoc
     *
     * .
     *
     */
    public function testCreateDoc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createHostedAsyncDoc
     *
     * .
     *
     */
    public function testCreateHostedAsyncDoc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createHostedDoc
     *
     * .
     *
     */
    public function testCreateHostedDoc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for expire
     *
     * .
     *
     */
    public function testExpire()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAsyncDoc
     *
     * .
     *
     */
    public function testGetAsyncDoc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAsyncDocStatus
     *
     * .
     *
     */
    public function testGetAsyncDocStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
